In [1]:
import tensorflow as tf
print(tf.__version__)

2.16.2


# First steps
A scalar is known as a rank 0 tensor because it has no dimensions (it's just a point)

The important point is knowing that tensors can hace an unlimited range of dimensions. The amount of dimensions will depend on the data we're trying to represent.

To create tensore there are 2 possibilities:
1. tf.Variable: Mutable tensor
2. tf.constant(): Inmutable tensor

In [4]:
#Create a scalar 
scalar = tf.constant(5)
print(scalar)

#Check the number of dimensions of the tensor 
print(f"Number of dimensions: {scalar.ndim}")

tf.Tensor(5, shape=(), dtype=int32)
Number of dimensions: 0


In [5]:
#Create a vector (more than 0 dimensions)
vector = tf.constant([10,10])
print(vector)

#Check the number of dimensions of the tensor 
print(f"Number of dimensions: {vector.ndim}")

tf.Tensor([10 10], shape=(2,), dtype=int32)
Number of dimensions: 1


In [6]:
#Create a matrix (more than 1 dimension)
matrix = tf.constant ([[10,10],[5,5]])
print(matrix)
#Check the number of dimensions of the tensor 
print(f"Number of dimensions: {matrix.ndim}")

tf.Tensor(
[[10 10]
 [ 5  5]], shape=(2, 2), dtype=int32)
Number of dimensions: 2


By default, Tensorflow creates tensor with either an int32 or float32 datatype. 

This approach can be an overkill solution for our problem


In [7]:
#Create another matrix and define the datatype
matrix_int8 = tf.constant([[10,10],[5,5]],dtype=tf.int8)
print(matrix_int8)

tf.Tensor(
[[10 10]
 [ 5  5]], shape=(2, 2), dtype=int8)


# Summary

- scalar: a single number.
- vector: a number with direction (e.g. wind speed with direction).
- matrix: a 2-dimensional array of numbers.
- tensor: an n-dimensional array of numbers (where n can be any number, a 0-d
dimension tensor is a scalar, a 1-dimension tensor is a vector).

## Random tensors
Some arbitrary size tensors which contain random numbers. This is what NN use to initialze their weights. 

In [8]:
#Create two random tensors (same content)
seed_1 = tf.random.Generator.from_seed(42) #set the seed for reproducibility
random_1 = seed_1.normal(shape=(3,2)) #create tensor from normal distribution
seed_2 = tf.random.Generator.from_seed(42)
random_2 = seed_2.normal(shape=(3,2))
print(random_1, random_2)
print(random_1 == random_2) #are they equal? 

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32) tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


In [9]:
#Create two random tensors (different content)
seed_3 = tf.random.Generator.from_seed(42) #set the seed for reproducibility
random_3 = seed_3.normal(shape=(3,2)) #create tensor from normal distribution
seed_4 = tf.random.Generator.from_seed(11)
random_4 = seed_4.normal(shape=(3,2))
print(random_3, random_4)
print(random_3 == random_4) #are they equal? 

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32) tf.Tensor(
[[ 0.27305737 -0.29925638]
 [-0.3652325   0.61883307]
 [-1.0130816   0.28291714]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[False False]
 [False False]
 [False False]], shape=(3, 2), dtype=bool)


In [10]:
#Shuffle a tensor (Intresting for non distributed dataset)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Gets different results each time
shuffled = tf.random.shuffle(not_shuffled)
print(not_shuffled, shuffled)

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32) tf.Tensor(
[[10  7]
 [ 2  5]
 [ 3  4]], shape=(3, 2), dtype=int32)


In [11]:
# Other ways to make tensors
# Tensor of all ones
ones = tf.ones([5,5]) 
print(f'Matrix of ones \n {ones}')

# Tensor of all zeros
zeros = tf.zeros([5,5])
print(f'Matrix of zeros\n {zeros}')

Matrix of ones 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Matrix of zeros
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU 

In [12]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int8) #Create a NumPy array between 1 and 25
print(f'Array: {numpy_A}')

A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2,3,4)) # The new elements must add up to give the same amount of elements as in the original
print(f'Tensor: {A}')
# X = tf.constant(matrix) # Capital letters for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Tensor: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


# Getting infromation from tensors

* Shape: Number of elements of each of the dimensions of a tensor
* Rank: Number of tensor dimensions
* Dimension: Particular dimension of a tensor
* Size: Total number of items in the tensor

In [13]:
#Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=([2, 3, 4,5]))
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [14]:
print(rank_4_tensor[0])

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)


In [15]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [16]:
# Get attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Sahpe of the tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print ("Elements along last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor", tf.size(rank_4_tensor))
print("Total number of elements in our tensor", tf.size(rank_4_tensor).numpy()) #Cleaner version for shape display

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Sahpe of the tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along last axis: 5
Total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor 120


# Indexing tensors
Tensors can be indexed just like Python list

In [17]:
# Get the first 2 eleements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [18]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [19]:
# Add an extra dimesion to our tensor
r_4_tensor = rank_4_tensor[...,tf.newaxis]
print(r_4_tensor)

#Alternativly to tf.newaxis
tf.expand_dims(rank_4_tensor, axis=-1)

tf.Tensor(
[[[[[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]]]



 [[[[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]
 

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
     

## Manipulating tensors(tensor operations)

### **Basic operations**

In [20]:

# You can add values to a tensor using the addition operator
tensor = tf.constant([[3,4],[1,4]])

# The base tansor is not modified 
#Addition
addition = tensor + 10 
print(addition)
#Substraction
substraction = tensor - 10 
print(substraction)
#Multiplication
multiplication = tensor * 10 
print(multiplication)
#Division
division = tensor + 10 
print(division)

tf.Tensor(
[[13 14]
 [11 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-7 -6]
 [-9 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[30 40]
 [10 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[13 14]
 [11 14]], shape=(2, 2), dtype=int32)


In [21]:
#Implementing Tensorflow built-in function
tf.multiply(tensor,10)
tf.math.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 14],
       [11, 14]], dtype=int32)>

## **Matrix multiplication**

In ML is one of the most common tensor operations. 

To multiply a matrix(tensor) by another matrix(tensor) we need to do the dot product of rows and columns. In dot products we multiply matching numbers and then sum up, eg: (1,2,3)*(7,9,11) = 1\*7+ 2\*9 + 3\*11 = 58

There are to rules our tensors needs to fullfil if we're going to matrix multiply them:
1. The inner dimenstion must match
2. The resulting matrix has the shape of the inner dimesions

In [22]:
# Matrix multiplication in tesnsorflow

tensor_a = tf.constant([[3,4],[1,4]])
tensor_b = tf.constant([[1,2],[3,4]])

tf.matmul(tensor_a, tensor_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 22],
       [13, 18]], dtype=int32)>

In [23]:
# Matrix multiplication with python operator "@"
tensor_a @ tensor_b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 22],
       [13, 18]], dtype=int32)>

In [24]:
# Create a tensor with 3,2 dimesnsions
tensor_c = tf.constant([[1,2],[3,4], [5,6]])
tensor_d = tf.constant([[10,20],[0,40], [5,6]])


#tf.matmul(tensor_c, tensor_d) # This matmul generates an error because we're violating rule one becuse the shape of both tensors are (3,2)

''' 
To compute the matmul operation a reshape of the tensor is required in order to follow the principle of inner dimsions has to be the same. 
For this particular example we need to achive 1 matrix with a shape of (3,2) and the other one with a shape of (2,3) to achive (3,2)(2,3)
'''
tensor_d_r = tf.reshape(tensor_d,(2,3))
tf.matmul(tensor_c,tensor_d_r)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 90,  30,  12],
       [190,  80,  24],
       [290, 130,  36]], dtype=int32)>

### The dot product
Matrix multiplication is also referred to as the dot product

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

Most of the time this type of operation will be done behing the scenes of your NN. Generally , you will transpose rather than reshape the tensor to satisfy the matrix multiplication rules.

In [ ]:
# Perform the dot product on tensor_c and tensor_d (requires transposing)
print(tensor_c,tensor_d)
tensor_c_t = tf.transpose(tensor_c)
print(tensor_c_t)

dp = tf.tensordot(tensor_c_t, tensor_d, axes=1)
print(dp)

In [39]:
# Perform the dot product on tensor_c and tensor_d (reshaping the tensor)
dp_s = tf.matmul(tf.reshape(tensor_c, shape=(2,3)), tensor_d)
print(dp_s)

tf.Tensor(
[[ 25 118]
 [ 70 316]], shape=(2, 2), dtype=int32)


In [45]:
#Check the values of tensor_c, reshape and transpose tensor_c
print("Normal tensor_c:", tensor_c)
print("Reshaped tensor_c to (2,3):", tf.reshape(tensor_c, shape=(2,3)))
print("Transposed tensor_c:", tf.transpose(tensor_c))

Normal tensor_c: tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Reshaped tensor_c to (2,3): tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Transposed tensor_c: tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


### Changing the datatype of a tensor


In [57]:
# Create a new tensor with default datatype (int32)
tensor_f32 = tf.constant([[1,2],[3,4], [5,6]])
print(tensor_f32.dtype)
#Change tensor precission to float16
tensor_f16 = tf.constant([[1,2],[3,4], [5,6]], dtype=tf.float16)
print(tensor_f16.dtype)

<dtype: 'int32'>
<dtype: 'float16'>


### Aggegrating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

Aggegation forms:
* Minimum
* Maximum
* Mean
* Sum
* etc.

In [61]:
# Get the absolute values 
A = tf.constant([[-1,2],[3,-4], [-5,6]])
abs_A = tf.abs(A)
print(abs_A)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [111]:
#Create a random tensor with values between 0 and 100 of size 50
A = tf.constant(np.random.randint(0,100, size=50), dtype=tf.float32)
# Get the minimum of the tensor
min_A = tf.reduce_min(A)
print(min_A)

#Get the maximum of the tensor
max_A = tf.reduce_max(A)
print(max_A)

#Get the mean of the tensor
mean_A = tf.reduce_mean(A)
print(mean_A)

#Get the sum of the tensor
sum_A = tf.reduce_sum(A)
print(sum_A)

#Variance and standard deviation of the tensor
var_A = tf.math.reduce_variance(A)
print("Variance: ", var_A)
dev_A = tf.math.reduce_std(A)
print("Deviation: ", dev_A)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(93.0, shape=(), dtype=float32)
tf.Tensor(52.86, shape=(), dtype=float32)
tf.Tensor(2643.0, shape=(), dtype=float32)
Variance:  tf.Tensor(853.52045, shape=(), dtype=float32)
Deviation:  tf.Tensor(29.215073, shape=(), dtype=float32)


### Find the positional maximum and minimum

In [113]:
#Create a new tensor for finding positional maximum and minumum
tf.random.set_seed(42)
B = tf.random.uniform(shape=[50])
print(B)

tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
 0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
 0.7381023  0.32054043], shape=(50,), dtype=float32)


In [121]:
#Find positional maximum
max_pos_B = tf.argmax(B)
print(max_pos_B)


#Index on our largest value position 
print(B[max_pos_B])
#Alternative
max_B = tf.reduce_max(B)
print(max_B)

tf.Tensor(42, shape=(), dtype=int64)
tf.Tensor(0.9671384, shape=(), dtype=float32)
tf.Tensor(0.9671384, shape=(), dtype=float32)


In [122]:
#Find positional minimum
min_pos_B = tf.argmin(B)
print(min_pos_B)


#Index on our largest value position 
print(B[min_pos_B])
#Alternative
min_B = tf.reduce_min(B)
print(min_B)

tf.Tensor(16, shape=(), dtype=int64)
tf.Tensor(0.009463668, shape=(), dtype=float32)
tf.Tensor(0.009463668, shape=(), dtype=float32)


## Squeeyze a tensor (removing all single dimensions)

In [133]:
#Create a random tensor
tf.random.set_seed(42)
C = tf.constant(tf.random.uniform(shape=[100]), shape=[1,1,1,100])
C

<tf.Tensor: shape=(1, 1, 1, 100), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043,
          0.6073899 , 0.46523476, 0.97803545, 0.7223145 , 0.32347047,
          0.82577336, 0.4976915 , 0.19483674, 0.7588748 , 0.3380444 ,
          0.28128064, 0.31513572, 0.60670924, 0.7498598 , 0.5016055 ,
          0.18282163, 0.13179815, 

In [135]:
#Squeeeze the single dimensions
C_squeezed = tf.squeeze(C)
print(C_squeezed.shape)

(100,)


### One-hot encoding tensors

In [139]:
#Create a list of indeces
some_list = [0,1,2] #Could represent colors like red,green, blue
depth = 3

#One-hot encode
tf.one_hot(some_list, depth)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

### Sqaring, log and sqare root

In [150]:
# Create a new tensor
D = tf.range(1,20, dtype=tf.float16)

#Square
sqr_D = tf.square(D) 
print(sqr_D)

#Squareroot (method requires non-int type)
sqrt_D = tf.sqrt(D)
print(sqrt_D)

#Log
log_D = tf.math.log(D)
print(log_D)

tf.Tensor(
[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121. 144. 169. 196.
 225. 256. 289. 324. 361.], shape=(19,), dtype=float16)
tf.Tensor(
[1.    1.414 1.732 2.    2.236 2.45  2.646 2.828 3.    3.162 3.316 3.465
 3.605 3.742 3.873 4.    4.125 4.242 4.36 ], shape=(19,), dtype=float16)
tf.Tensor(
[0.     0.6934 1.099  1.387  1.609  1.792  1.946  2.08   2.197  2.303
 2.398  2.484  2.564  2.639  2.709  2.773  2.834  2.89   2.945 ], shape=(19,), dtype=float16)


### Tensors and Numpy

The interoperability between the libraries is good. But we need to be concerned of some differences, such as the default data type is different between them.

**One of the main differences between them is that Tensorflow tensor can be run on a GPU or TPU for faste computation**

In [160]:
#Create a tensor directly from a Numpy array
E = tf.constant(np.array([3., 4.,5.]))
print(E)

#Convert back the tensor to Numpy array
arr_1 = np.array(E), type(np.array(E))
print(arr_1)
#Alternative
arr_2 = E.numpy(), type(E.numpy())
print(arr_2)

tf.Tensor([3. 4. 5.], shape=(3,), dtype=float64)
(array([3., 4., 5.]), <class 'numpy.ndarray'>)
(array([3., 4., 5.]), <class 'numpy.ndarray'>)


### Finding access to GPU

In [2]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]