In [5]:
import tensorflow as tf
print(tf.__version__)

2.20.0


# First steps
A scalar is known as a rank 0 tensor because it has no dimensions (it's just a point)

The important point is knowing that tensors can hace an unlimited range of dimensions. The amount of dimensions will depend on the data we're trying to represent.

To create tensore there are 2 possibilities:
1. tf.Variable: Mutable tensor
2. tf.constant(): Inmutable tensor

In [17]:
#Create a scalar 
scalar = tf.constant(5)
print(scalar)

#Check the number of dimensions of the tensor 
print(f"Number of dimensions: {scalar.ndim}")

tf.Tensor(5, shape=(), dtype=int32)
Number of dimensions: 0


In [20]:
#Create a vector (more than 0 dimensions)
vector = tf.constant([10,10])
print(vector)

#Check the number of dimensions of the tensor 
print(f"Number of dimensions: {vector.ndim}")

tf.Tensor([10 10], shape=(2,), dtype=int32)
Number of dimensions: 1


In [25]:
#Create a matrix (more than 1 dimension)
matrix = tf.constant ([[10,10],[5,5]])
print(matrix)
#Check the number of dimensions of the tensor 
print(f"Number of dimensions: {matrix.ndim}")

tf.Tensor(
[[10 10]
 [ 5  5]], shape=(2, 2), dtype=int32)
Number of dimensions: 2


By default, Tensorflow creates tensor with either an int32 or float32 datatype. 

This approach can be an overkill solution for our problem


In [27]:
#Create another matrix and define the datatype
matrix_int8 = tf.constant([[10,10],[5,5]],dtype=tf.int8)
print(matrix_int8)

tf.Tensor(
[[10 10]
 [ 5  5]], shape=(2, 2), dtype=int8)


# Summary

- scalar: a single number.
- vector: a number with direction (e.g. wind speed with direction).
- matrix: a 2-dimensional array of numbers.
- tensor: an n-dimensional array of numbers (where n can be any number, a 0-d
dimension tensor is a scalar, a 1-dimension tensor is a vector).

## Random tensors
Some arbitrary size tensors which contain random numbers. This is what NN use to initialze their weights. 

In [35]:
#Create two random tensors (same content)
seed_1 = tf.random.Generator.from_seed(42) #set the seed for reproducibility
random_1 = seed_1.normal(shape=(3,2)) #create tensor from normal distribution
seed_2 = tf.random.Generator.from_seed(42)
random_2 = seed_2.normal(shape=(3,2))
print(random_1, random_2)
print(random_1 == random_2) #are they equal? 

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32) tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


In [36]:
#Create two random tensors (different content)
seed_3 = tf.random.Generator.from_seed(42) #set the seed for reproducibility
random_3 = seed_3.normal(shape=(3,2)) #create tensor from normal distribution
seed_4 = tf.random.Generator.from_seed(11)
random_4 = seed_4.normal(shape=(3,2))
print(random_3, random_4)
print(random_3 == random_4) #are they equal? 

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32) tf.Tensor(
[[ 0.27305737 -0.29925638]
 [-0.3652325   0.61883307]
 [-1.0130816   0.28291714]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[False False]
 [False False]
 [False False]], shape=(3, 2), dtype=bool)


In [49]:
#Shuffle a tensor (Intresting for non distributed dataset)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Gets different results each time
shuffled = tf.random.shuffle(not_shuffled)
print(not_shuffled, shuffled)

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32) tf.Tensor(
[[ 3  4]
 [ 2  5]
 [10  7]], shape=(3, 2), dtype=int32)


In [9]:
# Other ways to make tensors
# Tensor of all ones
ones = tf.ones([5,5]) 
print(f'Matrix of ones \n {ones}')

# Tensor of all zeros
zeros = tf.zeros([5,5])
print(f'Matrix of zeros\n {zeros}')

Matrix of ones 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Matrix of zeros
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU 

In [19]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int8) #Create a NumPy array between 1 and 25
print(f'Array: {numpy_A}')

A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2,3,4)) # The new elements must add up to give the same amount of elements as in the original
print(f'Tensor: {A}')
# X = tf.constant(matrix) # Capital letters for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Tensor: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


# Getting infromation from tensors

* Shape: Number of elements of each of the dimensions of a tensor
* Rank: Number of tensor dimensions
* Dimension: Particular dimension of a tensor
* Size: Total number of items in the tensor

In [25]:
#Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=([2, 3, 4,5]))
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [26]:
print(rank_4_tensor[0])

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)


In [27]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [37]:
# Get attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Sahpe of the tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print ("Elements along last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor", tf.size(rank_4_tensor))
print("Total number of elements in our tensor", tf.size(rank_4_tensor).numpy()) #Cleaner version for shape display

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Sahpe of the tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along last axis: 5
Total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor 120


# Indexing tensors
Tensors can be indexed just like Python list

In [39]:
# Get the first 2 eleements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [43]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [48]:
# Add an extra dimesion to our tensor
r_4_tensor = rank_4_tensor[...,tf.newaxis]
print(r_4_tensor)

#Alternativly to tf.newaxis
tf.expand_dims(rank_4_tensor, axis=-1)

tf.Tensor(
[[[[[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]]]



 [[[[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]

   [[0.]
    [0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]
 

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
     

## Manipulating tensors(tensor operations)

### **Basic operations**

In [10]:

# You can add values to a tensor using the addition operator
tensor = tf.constant([[3,4],[1,4]])

# The base tansor is not modified 
#Addition
addition = tensor + 10 
print(addition)
#Substraction
substraction = tensor - 10 
print(substraction)
#Multiplication
multiplication = tensor * 10 
print(multiplication)
#Division
division = tensor + 10 
print(division)

tf.Tensor(
[[13 14]
 [11 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-7 -6]
 [-9 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[30 40]
 [10 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[13 14]
 [11 14]], shape=(2, 2), dtype=int32)


In [12]:
#Implementing Tensorflow built-in function
tf.multiply(tensor,10)
tf.math.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 14],
       [11, 14]], dtype=int32)>

## ** Matrix multiplication**

In ML is one of the most common tensor operations. 

To multiply a matrix(tensor) by another matrix(tensor) we need to do the dot product of rows and columns. In dot products we multiply matching numbers and then sum up, eg: (1,2,3)*(7,9,11) = 1\*7+ 2\*9 + 3\*11 = 58

There are to rules our tensors needs to fullfil if we're going to matrix multiply them:
1. The inner dimenstion must match
2. The resulting matrix has the shape of the inner dimesions

In [28]:
# Matrix multiplication in tesnsorflow

tensor_a = tf.constant([[3,4],[1,4]])
tensor_b = tf.constant([[1,2],[3,4]])

tf.matmul(tensor_a, tensor_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 22],
       [13, 18]], dtype=int32)>

In [15]:
# Matrix multiplication with python operator "@"
tensor_a @ tensor_b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 22],
       [13, 18]], dtype=int32)>

In [33]:
# Create a tensor with 3,2 dimesnsions
tensor_c = tf.constant([[1,2],[3,4], [5,6]])
tensor_d = tf.constant([[10,20],[0,40], [5,6]])


#tf.matmul(tensor_c, tensor_d) # This matmul generates an error because we're violating rule one becuse the shape of both tensors are (3,2)

''' 
To compute the matmul operation a reshape of the tensor is required in order to follow the principle of inner dimsions has to be the same. 
For this particular example we need to achive 1 matrix with a shape of (3,2) and the other one with a shape of (2,3) to achive (3,2)(2,3)
'''
tensor_d_r = tf.reshape(tensor_d,(2,3))
tf.matmul(tensor_c,tensor_d_r)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 90,  30,  12],
       [190,  80,  24],
       [290, 130,  36]], dtype=int32)>