In [10]:
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

--2026-04-05 18:28:03--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8000::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2026-04-05 18:28:04 (141 MB/s) - ‘helper_functions.py’ saved [10246/10246]



In [12]:
from helper_functions import create_tensorboard_callback, plot_loss_curves, unzip_data, walk_through_dir

In [13]:
!wget https://storage.googleapis.com/ztm_tf_course/food_vision/10_food_classes_10_percent.zip

--2026-04-05 18:34:05--  https://storage.googleapis.com/ztm_tf_course/food_vision/10_food_classes_10_percent.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 2a00:1450:4005:803::201b, 2a00:1450:4005:804::201b, 142.250.201.187, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2a00:1450:4005:803::201b|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 168546183 (161M) [application/zip]
Saving to: ‘10_food_classes_10_percent.zip.1’

10_food_classes_10_ 100%[===================>] 160.74M  18.5MB/s    in 11s     

2026-04-05 18:34:17 (14.7 MB/s) - ‘10_food_classes_10_percent.zip.1’ saved [168546183/168546183]



In [17]:
unzip_data("10_food_classes_10_percent.zip")

In [16]:
walk_through_dir("10_food_classes_10_percent/")

There are 2 directories and 0 images in '10_food_classes_10_percent/'.
There are 10 directories and 0 images in '10_food_classes_10_percent/train'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/fried_rice'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/hamburger'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/chicken_curry'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/sushi'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/ramen'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/ice_cream'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/chicken_wings'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/steak'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/grilled_salmon'.
There are 0 directories and 75 images in '10_food_classes_10_percen

In [19]:
# Create training and test directory paths 

test_dir = "10_food_classes_10_percent/test/"
train_dir = "10_food_classes_10_percent/train/"

In [26]:
import tensorflow as tf

IMG_SIZE = (224,224)
BATCH_SIZE = 32
train_data_10_percent = tf.keras.preprocessing.image_dataset_from_directory(directory = train_dir,
                                                                           image_size = IMG_SIZE,
                                                                           label_mode= "categorical",
                                                                           batch_size= BATCH_SIZE)

test_data_10_percent = tf.keras.preprocessing.image_dataset_from_directory(directory= test_dir,
                                                                          image_size= IMG_SIZE,
                                                                          label_mode= "categorical",
                                                                          batch_size= BATCH_SIZE)

Found 750 files belonging to 10 classes.
Found 2500 files belonging to 10 classes.


In [28]:
train_data_10_percent
train_data_10_percent.class_names

['chicken_curry',
 'chicken_wings',
 'fried_rice',
 'grilled_salmon',
 'hamburger',
 'ice_cream',
 'pizza',
 'ramen',
 'steak',
 'sushi']

In [58]:
# See an example of a batch of data
for images, labels in train_data_10_percent.take(1):
    print(images, labels)

tf.Tensor(
[[[[7.22091827e+01 5.42091827e+01 3.04642868e+01]
   [7.42040863e+01 5.71785736e+01 3.12295952e+01]
   [9.75561295e+01 7.73418427e+01 5.00663300e+01]
   ...
   [2.32091045e+01 1.57805767e+01 5.99484062e+00]
   [2.37346840e+01 1.67346840e+01 6.73468447e+00]
   [1.88723660e+01 1.18723669e+01 1.87236679e+00]]

  [[5.80969353e+01 4.16938782e+01 1.99540806e+01]
   [1.04852043e+02 8.88469391e+01 6.41377563e+01]
   [9.93928604e+01 8.17500000e+01 5.41071434e+01]
   ...
   [2.69438763e+01 2.09438763e+01 8.94387627e+00]
   [2.67091560e+01 1.97091560e+01 9.70915699e+00]
   [1.84998608e+01 1.14998608e+01 1.88255095e+00]]

  [[8.65969391e+01 7.03826447e+01 5.36785660e+01]
   [8.05204086e+01 6.52346954e+01 4.55918388e+01]
   [1.04352051e+02 8.76632690e+01 6.38979645e+01]
   ...
   [2.71683273e+01 2.11683273e+01 8.83162785e+00]
   [2.40560932e+01 1.78418083e+01 6.27037954e+00]
   [1.97039967e+01 1.34897108e+01 2.07135868e+00]]

  ...

  [[7.92904510e+01 6.29486427e+01 3.66578674e+01]
   [8